### ISSUE TITLE
When moonlight closes, my other monitors and main monitors resolution will not return to normal.

### ISSUE THREAD

**Issue by grrminator** [hansschmucker/NVStreamer1080#1]
Title.

After closing moonlight client, I have to dp Wondows key + P to return monitors to normal, and then force them back to the correct resolution if they are not 1920x1080 default.

**Comment by hansschmucker** [comment]
Hi

Could you try again with the current release?
https://github.com/hansschmucker/NVStreamer1080/releases/tag/v1.1.0.0
I've added a bit of logging and fixed one issue where "Second Screen" behavior after it had already initialized, meaning that the app would switch to the second screen but upon streaming end would instead change the resolution.

**Comment by grrminator** [comment]
Alright! Will try it out!

**Comment by grrminator** [comment]
How does one uninstall the previous version?

**Comment by hansschmucker** [comment]
Just close it from the Systray. There's an ugly icon there while it is running. Right click that and chose Exit.
Copy the new version to the same place (or anywhere really.. it will overwrite the previous registration on first run) and start it.

**Comment by hansschmucker** [comment]
![image](https://user-images.githubusercontent.com/248554/183489480-43ea3864-eacb-4761-ab6a-016416ec9919.png)

**Comment by grrminator** [comment]
It does not return my 3 monitors to normal after ending the stream still.

**Comment by hansschmucker** [comment]
Oh, three screens?
Probably won't work. For second screen switching, all it does is switch to "External" on connect and back to "Internal" on disconnect. So if that's not what you need then it won't help you I'm afraid.

You can try yourself by hitting Win+P and selecting "external", then hitting Win+P again and selecting "internal".

Does this what you want?

**Comment by hansschmucker** [comment]
Closed because 3 monitor setups are out of scope.

**Comment by grrminator** [comment]
I will attempt it when I can. Stuck back at work haha.
