### ISSUE TITLE
Opening NVStreamer with administrator permissions closes the Sunshine service

### ISSUE THREAD

**Issue by bashbers** [hansschmucker/NVStreamer1080#20]
Whenever I open NVStreamer, whether its on boot or manually, it kills the sunshine service in services.msc

**Comment by hansschmucker** [comment]
Hi Brian
That's actually by design.
It's supposed to spawn Sunshine again as a subprocess so that it can
monitor standard out.

Just to make sure: You've specified the sunshine exe as path and it's not
doing that?
