### ISSUE TITLE
Auto hibernate/sleep/shutdown after session ends

### ISSUE THREAD

**Issue by SuperLeiyan** [hansschmucker/NVStreamer1080#5]
It would be useful to have a configurable timer to auto hibernate/sleep/shutdown after a stream ends.
Stop the timer if the user starts another stream(switched to another game) or moves the cursor(user is back on the computer).

**Comment by hansschmucker** [comment]
That makes so much sense it seems unforgivable that it isn't standard... I'll try to get it done tonight ^^

**Comment by hansschmucker** [comment]
Just for reference: Still haven't been able to test it yet, but it should work.
I'll leave this open until I've tested and packaged the next version.

--hans

**Comment by hansschmucker** [comment]
Tested and released. Closing :)
